# Base URL for patient API
@baseUrl = http://localhost:7094

POST {{baseUrl}}/api/v1/sapphire/organization/4:584fe225-8704-4f61-b2b6-1cce33b0b662:11079/network/4:584fe225-8704-4f61-b2b6-1cce33b0b662:3048/location/_search

> {%
    const apiResponse = response.body;
    console.log("API Response:", apiResponse);
%}

###